### ISSUE TITLE
pyphy package issue

### ISSUE THREAD

**Issue by varsha1288** [dgg32/neo4j_genome_ko#1]
Hi

I was just working with this repo. I was able to install Phyphy and import it. However I get an error at this line 60
getDictPathByTaxid.

dict_path = phyphy.getDictPathByTaxid(taxid)
AttributeError: module 'phyphy' has no attribute 'getDictPathByTaxid'

Are we missing this function in the code? getDictPathByTaxid.

Please let me know.

Thanks,
Varsha

**Comment by dgg32** [comment]
@varsha1288 Thank you for pointing out the dependency. You need the [pyphy](https://github.com/dgg32/pyphy) library for this task. Please go to [pyphy](https://github.com/dgg32/pyphy) and prepare both the data and the library. Don't forget to add its source folder to PYTHONPATH. So modify this line below and append it to your ~/.bashrc. 

```
export PYTHONPATH="${PYTHONPATH}:/my/own/pyphy/source/"
```

It should solve this error. 

I have also updated the readme. Thank you very much!

BTW, it is "pyphy" not "phyphy".

If you have any problem or question, please do not hesitate to ask. I will be here to assist you.

Greetings!

**Comment by varsha1288** [comment]
Thank you for linking this. I wasn't sure what it was. I saw there was a package phyphy used with biopython.

Thanks for the update. Will try this out.

**Comment by dgg32** [comment]
@varsha1288 I will try to register the pyphy in pip and conda. I am currently with hotel wifi, so please be patient and I will do that when I get a stable internet connection.

**Comment by varsha1288** [comment]
@dgg32 Thank you so much! pip installing that package would be great and straightforward.

Thanks,
Varsha

**Comment by dgg32** [comment]
@varsha1288 Hi. I have made the package to pypi. Please install the package via
```
pip install pyphy
```

But you still need to prepare the database for pyphy to work.

After the pip installation, use the following command to see where it is installed:
```
pip show pyphy
```

In my case, it shows "/Users/dgg32/opt/anaconda3/lib/python3.8/site-packages"

Download the NCBI taxdmp.zip and unpack it, and run 
```
python /Users/dgg32/opt/anaconda3/lib/python3.8/site-packages/pyphy/prepyphy.py [ncbi_taxdmp_folder] [db_path]
```

You will be all set!

**Comment by varsha1288** [comment]
Thanks so much! Appreciate it.
